# PreToolUse hook (matcher: Edit|Write|MultiEdit).
# Blocks (1) edits to generated EF files and (2) secrets landing in appsettings*.json.
# Reads the tool-call JSON from stdin; exit 2 blocks the call (stderr is shown to Claude).

$ErrorActionPreference = 'Stop'

$raw = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }

try {
    $payload = $raw | ConvertFrom-Json
} catch {
    exit 0
}

$filePath = [string]$payload.tool_input.file_path
if ([string]::IsNullOrWhiteSpace($filePath)) { exit 0 }

# Use forward slashes so path patterns are consistent regardless of OS separator.
$normalizedPath = $filePath -replace '\\', '/'

# ---- 1. Generated EF files ----
$efPatterns = @(
    '/Migrations/.*\.Designer\.cs$',   # migration designer files
    '/Migrations/\d.*\.cs$',           # timestamped migration bodies (e.g. 20240101_Init.cs)
    'VacaYAYDbContextModelSnapshot\.cs$'
)
foreach ($p in $efPatterns) {
    if ($normalizedPath -imatch $p) {
        [Console]::Error.WriteLine(
            "Blocked: generated EF file. Change the entity / OnModelCreating instead; " +
            "the migration is regenerated by a human (see CLAUDE.md Guardrails).")
        exit 2
    }
}

# ---- 2. Secrets in appsettings ----
if ($normalizedPath -imatch '/appsettings.*\.json$') {
    # Gather all content the tool would write. Write => .content; Edit => .new_string;
    # MultiEdit => .edits[].new_string.
    $chunks = @()
    if ($payload.tool_input.content)    { $chunks += [string]$payload.tool_input.content }
    if ($payload.tool_input.new_string) { $chunks += [string]$payload.tool_input.new_string }
    if ($payload.tool_input.edits) {
        foreach ($e in $payload.tool_input.edits) {
            if ($e.new_string) { $chunks += [string]$e.new_string }
        }
    }
    $content = ($chunks -join "`n")

    # A populated "SigningKey": "..." or "DefaultConnection": "..." (non-empty value).
    if ($content -imatch '"SigningKey"\s*:\s*"[^"]+"' -or
        $content -imatch '"DefaultConnection"\s*:\s*"[^"]+"') {
        [Console]::Error.WriteLine(
            "Blocked: secrets belong in user-secrets, not appsettings (see CLAUDE.md Guardrails). " +
            "Use: dotnet user-secrets set `"<key>`" `"<value>`" --project src/VacaYAY.Api")
        exit 2
    }
}

exit 0
