namespace VacaYAY.Business.DTOs.Employee;

/// <summary>
/// HR provisions a new employee account. The one-time temp password is generated by the system
/// (not supplied here) and returned once in the create response; the account has no
/// <c>PasswordHash</c> until the employee sets their own on first login.
/// </summary>
public class CreateEmployeeRequest
{
    public string FirstName { get; set; } = string.Empty;

    public string LastName { get; set; } = string.Empty;

    public string Email { get; set; } = string.Empty;

    public UserRole Role { get; set; }

    public string? Department { get; set; }

    public string? JobTitle { get; set; }

    public DateTime? HireDate { get; set; }

    public DateTime? EmploymentStartDate { get; set; }

    public DateTime? EmploymentEndDate { get; set; }

    public int DaysOff { get; set; }
}
